---
- hosts: firstmanager
  become_user: qss
  tasks:
    - name: create the first ucp manager
      shell: >
       docker container run --rm -t --name ucp
       -v /var/run/docker.sock:/var/run/docker.sock
       docker/ucp:2.2.5 install
       --host-address 10.16.20.2
       --admin-username admin
       --admin-password password1
       --san ucpdr.qloudableincdr.com > ucp.log 2>&1
    - name: create the first ucp manager
      shell: >
        cat ucp.log
